[package]
name = "kreqo-core"
version = "0.0.0"
edition.workspace = true

[dependencies]
argon2.workspace = true
chrono.workspace = true
serde.workspace = true
server_fn.workspace = true
sqlx.workspace = true
thiserror.workspace = true
xilem.workspace = true
