[package]
name = "kreqo-learn"
version = "0.0.0"
edition.workspace = true

[dependencies]
server_fn.workspace = true
xilem.workspace = true

kreqo-core.workspace = true
kreqo-server.workspace = true
kreqo-ui.workspace = true
